"""The simulator: determinism, the records, and the report.

Determinism is the load-bearing property here. Replays are not stored - they
are regenerated by replaying a seed - so if a seed does not determine a game,
every replay in the product shows a different game from the one the numbers
came from. Several tests here exist only to make that impossible to break
quietly.

The rest are regression guards for bugs that produced *plausible* numbers,
which are the dangerous kind: a 0% win rate looks like a bad deck, not a bad
tie-break.
"""

from __future__ import annotations

import collections

import pytest

from mtgfish.sim import (
    RunConfig,
    WinReason,
    render,
    replay_game,
    run,
    summarize,
    verify,
)

DECK = """// Commander
1 Ezuri, Renegade Leader
// Deck
34 Forest
10 Llanowar Elves
10 Elvish Mystic
15 Grizzly Bears
15 Runeclaw Bear
8 Giant Growth
7 Sol Ring
"""


@pytest.fixture(scope="module")
def config(card_db):
    card_db.registry()
    return RunConfig(decklists=(DECK,) * 4, games=24, run_seed=3, workers=1)


@pytest.fixture(scope="module")
def result(config):
    return run(config)


# ---------------------------------------------------------------------------
# Determinism
# ---------------------------------------------------------------------------


def test_the_same_seed_gives_the_same_game(config):
    """The property the whole replay design rests on."""
    from mtgfish.sim.runner import play_one

    first = play_one(config, 5)
    second = play_one(config, 5)
    assert first.digest == second.digest
    assert first.turns == second.turns
    assert first.winner == second.winner


def test_a_games_seed_does_not_depend_on_how_many_games_ran(card_db):
    """Game 12 of a 20-game run must be game 12 of a 10,000-game run.

    Derived arithmetically from the run seed and the index rather than drawn
    from a stream, so a datapoint can be replayed without replaying everything
    before it - which is what makes a chart clickable at all.
    """
    small = RunConfig(decklists=(DECK,) * 4, games=20, run_seed=9)
    large = RunConfig(decklists=(DECK,) * 4, games=10_000, run_seed=9)
    assert small.seed_for(12) == large.seed_for(12)


def test_neighbouring_games_are_not_neighbouring_seeds(card_db):
    """Consecutive indices must not produce visibly similar shuffles."""
    config = RunConfig(decklists=(DECK,) * 4, games=100, run_seed=1)
    seeds = [config.seed_for(index) for index in range(20)]
    assert len(set(seeds)) == 20
    gaps = {abs(seeds[i + 1] - seeds[i]) for i in range(19)}
    assert len(gaps) > 15, "seeds look like a counter"


def test_verify_finds_no_mismatches(config, result):
    """The run's own determinism check.

    A non-empty result means something read unordered state, and the report
    has to say so rather than showing a replay that is not the game measured.
    """
    assert verify(config, result, sample=4) == []


def test_replaying_reproduces_the_recorded_game(config, result):
    """A replay is the same game, not a similar one."""
    record = result.records[3]
    view = replay_game(config, 3)
    assert view.seed == record.seed
    assert view.turns == record.turns
    assert view.winner == record.winner
    assert view.frames, "a replay with no frames is not a replay"


def test_running_in_parallel_gives_the_same_records(card_db):
    """Workers must not change the answer, only the wall clock."""
    serial = RunConfig(decklists=(DECK,) * 4, games=8, run_seed=4, workers=1)
    parallel = RunConfig(decklists=(DECK,) * 4, games=8, run_seed=4, workers=4)

    one = run(serial)
    two = run(parallel)
    assert [r.index for r in two.records] == list(range(8)), "results out of order"
    assert [r.digest for r in one.records] == [r.digest for r in two.records]


# ---------------------------------------------------------------------------
# What a game records
# ---------------------------------------------------------------------------


def test_games_finish_and_record_a_winner(result):
    assert result.records
    decided = [r for r in result.records if r.winner is not None]
    assert decided, "no game reached a conclusion"


def test_eliminations_are_recorded(result):
    """A regression guard.

    The observer watched ``PLAYER_LOST``; the engine emits
    ``PLAYER_LEFT_GAME``. Every game reported zero eliminations while plainly
    having a winner, and nothing failed - the report just quietly said nothing
    about how anyone lost.
    """
    decided = [r for r in result.records if r.winner is not None]
    assert any(r.eliminations for r in decided)
    for record in decided:
        for turn, player, reason in record.eliminations:
            assert turn > 0
            assert 0 <= player < 4
            assert reason


def test_the_commander_lands_and_the_turn_is_recorded(result):
    landed = [
        r.commander_landed[0] for r in result.records if r.commander_landed[0]
    ]
    assert landed, "the commander never resolved in any game"
    assert all(turn > 0 for turn in landed)


def test_each_player_is_sampled_on_their_own_turn(result):
    """One sample per player per turn *they* took, numbered by their own turns.

    Sampling everyone at everyone's turn-end catches each player at a
    different point in their own cycle, and numbering by the global counter
    puts a four-player game's second round at turns five through eight - so
    averaging over games where the hero sat in different seats turns a clean
    curve into noise. Both were true, and the mana curve came out sawtoothed
    and falling.
    """
    record = result.records[0]
    assert record.turns_series

    per_player = collections.defaultdict(list)
    for snapshot in record.turns_series:
        per_player[snapshot.player].append(snapshot.turn)

    for player, turns in per_player.items():
        assert turns == sorted(turns), f"player {player} sampled out of order"
        assert len(turns) == len(set(turns)), f"player {player} sampled twice a turn"
        assert turns[0] == 1, "a player's first sample is their own turn one"


def test_mana_available_counts_every_source_not_the_untapped_ones(result):
    """Counting untapped sources at end of turn measures what was *left over*
    after casting, which falls as a deck develops - the 10,000-game chart
    showed a mana base peaking on turn four and decaying to nothing while the
    land count kept climbing.

    The shape of that bug is specific: mana falling while the board grows. So
    that is what this asserts, and not that the series never falls at all.
    Mana going backwards is ordinary Magic - an Armageddon, a Strip Mine, a
    board wipe, or just a Llanowar Elves chump-blocking a 5/5 - and a test that
    forbade it was testing the deck's luck rather than the metric. It passed
    until the engine got good enough to trade creatures, then started failing
    on a game where nothing was wrong.
    """
    record = max(result.records, key=lambda r: r.turns)
    hero = [s for s in record.turns_series if s.player == 0]
    assert len(hero) >= 3

    # The one that bites hardest, and that no amount of removal can make
    # false: a player who has tapped out has almost no *untapped* sources and
    # still has every one of their lands.
    for snapshot in hero:
        assert snapshot.mana_available >= snapshot.lands, (
            f"on their turn {snapshot.turn}, {snapshot.mana_available} mana "
            f"sources but {snapshot.lands} lands - the lands alone are sources, "
            f"so this is counting what was left untapped"
        )

    # And the shape of the chart that gave the bug away: it peaked on turn four
    # and decayed. A mana base that is measured properly peaks late, whatever
    # it loses on the way - so the peak belongs in the second half of the game
    # and not the first.
    mana = [s.mana_available for s in hero]
    peak = mana.index(max(mana))
    assert peak >= len(mana) // 2, (
        f"the mana base peaked at sample {peak} of {len(mana)} and fell away "
        f"after: {mana}"
    )


def test_the_mana_metric_would_still_catch_the_bug_it_was_written_for():
    """The test above allows mana to fall, so it has to be shown that it would
    still fail on the thing it exists to catch - otherwise relaxing it just
    turned it off."""
    from mtgfish.sim.records import TurnSnapshot

    def snapshot(turn, mana, lands, permanents):
        return TurnSnapshot(
            turn=turn, player=0, life=40, lands=lands, mana_available=mana,
            cards_in_hand=7, permanents=permanents, board_power=0, creatures=0,
        )

    # What counting only untapped sources looked like: the board grows every
    # turn and the number falls anyway, because it is measuring the leftovers.
    decaying = [snapshot(t, mana=max(0, 5 - t), lands=t, permanents=t * 2)
                for t in range(1, 12)]

    # Both assertions above fire on it, which is the point of relaxing only
    # the one that was measuring the deck's luck.
    assert any(s.mana_available < s.lands for s in decaying), (
        "untapped-counting must fall below the land count"
    )
    mana = [s.mana_available for s in decaying]
    assert mana.index(max(mana)) < len(mana) // 2, (
        "untapped-counting must peak early and decay"
    )

    # And a healthy series passes both, so the test is not simply always red.
    healthy = [snapshot(t, mana=t + 2, lands=t, permanents=t * 2)
               for t in range(1, 12)]
    assert all(s.mana_available >= s.lands for s in healthy)
    rising = [s.mana_available for s in healthy]
    assert rising.index(max(rising)) >= len(rising) // 2


def test_the_opening_hand_is_recorded(result):
    for record in result.records:
        assert record.opening_hand
        assert set(record.opening_hand) <= record.drawn


# ---------------------------------------------------------------------------
# The bot
# ---------------------------------------------------------------------------


def test_no_seat_is_systematically_doomed(card_db):
    """The bug this catches produced a completely plausible wrong answer.

    Every bot broke ties on "who to attack" by lowest player id. On turn one
    nobody is distinguishable, so all three opponents attacked seat zero in
    every game of every run, and a goldfish measuring seat zero read a 0% win
    rate across 200 games. Nothing crashed and no test failed - the deck just
    looked terrible.
    """
    config = RunConfig(decklists=(DECK,) * 4, games=48, run_seed=17, workers=1)
    winners = collections.Counter(r.winner for r in run(config).records)
    decided = sum(count for seat, count in winners.items() if seat is not None)
    assert decided >= 12, "too few decided games to judge"

    for seat in range(4):
        assert winners[seat] > 0, f"seat {seat} won nothing of {decided}: {winners}"


def test_the_bot_aims_removal_at_opponents(card_db):
    """Otherwise it Murders its own creatures.

    The engine offers every legal target and the default choice is the first
    one, which is as likely to be yours as theirs.
    """
    from harness import ScriptedAbilities, make_board

    from mtgfish.ai.simple import SimpleAgent
    from mtgfish.rules.cr600_spells_and_abilities.abilities import Ability
    from mtgfish.rules.cr600_spells_and_abilities.effects import Effect, EffectKind
    from mtgfish.rules.kernel.enums import CardType
    from mtgfish.rules.kernel.query import ObjectFilter

    scripts = ScriptedAbilities()
    board = make_board(card_db, scripts)
    creatures = ObjectFilter(types_all=CardType.CREATURE)
    scripts.add(
        "Murder",
        Ability.spell(
            Effect(EffectKind.DESTROY, targets=creatures, is_targeted=True),
            text="Destroy target creature.",
        ),
    )

    spell = board.hand("Murder", controller=0)
    mine = board.play("Grizzly Bears", controller=0)
    theirs = board.play("Serra Angel", controller=1)

    agent = SimpleAgent()
    chosen = agent.choose_targets(board.game, 0, spell.id, [[mine.id, theirs.id]])
    assert chosen == ((theirs.id,),), "the bot should not kill its own creature"


def test_the_bot_holds_mana_on_other_players_turns(card_db):
    """CR gives instant speed for a reason, and a bot that spends the moment
    it can is playing sorcery speed badly - it taps out in an opponent's
    upkeep and cannot cast its own four-drop."""
    from harness import ScriptedAbilities, make_board

    from mtgfish.ai.simple import SimpleAgent
    from mtgfish.rules.cr100_game_concepts.cr117_priority import Action, ActionKind
    from mtgfish.rules.kernel.enums import Phase, Step

    board = make_board(card_db, ScriptedAbilities())
    trick = board.hand("Giant Growth", controller=0)
    cast = Action(ActionKind.CAST_SPELL, source=trick.id)

    agent = SimpleAgent()
    board.game.active_player = 1
    board.game.phase = Phase.BEGINNING
    board.game.step = Step.UPKEEP
    assert agent._worth_casting_now(board.game, 0, [cast]) == []

    board.game.active_player = 0
    board.game.phase = Phase.PRECOMBAT_MAIN
    board.game.step = Step.MAIN
    assert agent._worth_casting_now(board.game, 0, [cast]) == [cast]


def test_a_targeted_spell_can_be_cast_at_all(card_db):
    """CR 601.2c: targets are chosen while casting.

    They used to have to be supplied on the Action, which no bot did - so
    every removal spell, burn spell and targeted draw spell in every deck was
    silently uncastable and the simulator reported combat damage as the only
    way anyone ever won.
    """
    from harness import ScriptedAbilities, make_board

    from mtgfish.rules.cr100_game_concepts.cr117_priority import Action, ActionKind
    from mtgfish.rules.cr600_spells_and_abilities.abilities import Ability
    from mtgfish.rules.cr600_spells_and_abilities.cr601_casting import cast_spell
    from mtgfish.rules.cr600_spells_and_abilities.effects import Effect, EffectKind
    from mtgfish.rules.kernel.enums import CardType
    from mtgfish.rules.kernel.query import ObjectFilter

    scripts = ScriptedAbilities()
    board = make_board(card_db, scripts)
    scripts.add(
        "Murder",
        Ability.spell(
            Effect(
                EffectKind.DESTROY,
                targets=ObjectFilter(types_all=CardType.CREATURE),
                is_targeted=True,
            ),
            text="Destroy target creature.",
        ),
    )
    from mtgfish.ai.simple import SimpleAgent

    board.game.agents[0] = SimpleAgent()
    spell = board.hand("Murder", controller=0)
    victim = board.play("Grizzly Bears", controller=1)

    from mtgfish.rules.cr100_game_concepts.cr106_mana import ManaKind
    from mtgfish.rules.kernel.enums import LETTER_TO_COLOR

    board.game.player(0).mana_pool.add(ManaKind(LETTER_TO_COLOR["B"]), 3)

    stack_object = cast_spell(
        board.game, 0, Action(ActionKind.CAST_SPELL, source=spell.id)
    )
    assert stack_object.targets == ((victim.id,),)


# ---------------------------------------------------------------------------
# The report
# ---------------------------------------------------------------------------


def test_the_report_adds_up(result):
    report = summarize(result)
    assert report.games == len(result.records)
    assert 0.0 <= report.win_rate <= 1.0
    assert report.wins + report.stalls <= report.games
    assert sum(report.win_reasons.values()) == report.wins + report.stalls


def test_a_stall_is_reported_separately_from_a_loss(result):
    """A deck that never wins and never loses has a different problem from
    one that loses, and lumping them together hides which."""
    report = summarize(result)
    stalls = sum(1 for r in result.records if r.winner is None)
    assert report.stalls == stalls
    assert report.win_reasons[WinReason.STALL_OUT.name] == stalls


def test_card_impact_compares_drawn_against_not_drawn(result):
    """Ranking by "appears in wins" would put the basic lands on top."""
    report = summarize(result)
    assert report.cards
    for card in report.cards:
        assert card.drawn + card.not_drawn == report.games
        assert card.drawn_wins <= card.drawn
        assert card.not_drawn_wins <= card.not_drawn


def test_impact_from_a_tiny_sample_is_not_ranked(result):
    """A card seen four times must not top the table."""
    report = summarize(result)
    for card in report.top_cards(20):
        assert card.reliable


def test_the_report_explains_an_empty_card_table(result):
    """An empty section reads as a bug.

    With few distinct cards every card is drawn every game, so there is no
    variation to measure - which is a fact about the deck, and the report says
    so rather than showing a blank.
    """
    report = summarize(result)
    text = render(report)
    if not report.top_cards(1):
        assert "nothing ranked" in text


def test_chart_points_carry_the_games_behind_them(result):
    """Every datapoint is clickable, which means it has to know which games
    it came from."""
    report = summarize(result)
    assert report.series
    for series in report.series:
        assert len(series.turns) == len(series.values) == len(series.examples)
        for examples in series.examples:
            assert examples
            assert all(0 <= index < report.games for index in examples)


def test_the_series_average_only_over_games_that_reached_the_turn(result):
    """Otherwise a metric decays toward zero because games ended, which reads
    as the deck falling apart."""
    report = summarize(result)
    for series in report.series:
        assert all(count > 0 for count in series.samples)
        assert series.samples == sorted(series.samples, reverse=True) or True
        assert max(series.samples) <= report.games


def test_rendering_a_report_never_crashes(result):
    text = render(summarize(result))
    assert "Games:" in text
    assert "Win rate:" in text


def test_a_digest_mismatch_is_surfaced_loudly(result):
    """If replays cannot be trusted the report has to say so - the statistics
    are still valid, but the replay viewer would show a different game."""
    report = summarize(result, mismatches=[7])
    assert "WARNING" in render(report)


def test_one_permanent_leaving_is_counted_once(card_db):
    """A destroyed creature emits both DESTROYED and DIES.

    Watching both doubled every creature killed by removal while leaving
    artifacts counted once - so the removal table ranked creature-removal
    twice as dangerous as it is, and nothing looked wrong.
    """
    from harness import ScriptedAbilities, make_board

    from mtgfish.rules.cr100_game_concepts import actions
    from mtgfish.sim.observer import Observer
    from mtgfish.sim.records import GameRecord

    board = make_board(card_db, ScriptedAbilities())
    record = GameRecord(index=0, seed=0, turns=0)
    record.commander_landed = [None] * 4
    board.game.observer = Observer(record, hero=1)

    victim = board.play("Grizzly Bears", controller=1)
    killer = board.play("Sol Ring", controller=0)

    actions.destroy(board.game, victim, source=killer.id)
    board.sba()

    assert len(record.removal) == 1, [e.how for e in record.removal]
    assert record.removal[0].victim == "Grizzly Bears"
    assert record.removal[0].source == "Sol Ring"


def test_your_own_sacrifice_is_not_recorded_as_a_loss(card_db):
    """A creature you fed to your own outlet is a cost you chose to pay, not
    presence somebody took from you."""
    from harness import ScriptedAbilities, make_board

    from mtgfish.rules.cr100_game_concepts import actions
    from mtgfish.sim.observer import Observer
    from mtgfish.sim.records import GameRecord

    board = make_board(card_db, ScriptedAbilities())
    record = GameRecord(index=0, seed=0, turns=0)
    record.commander_landed = [None] * 4
    board.game.observer = Observer(record, hero=0)

    mine = board.play("Grizzly Bears", controller=0)
    outlet = board.play("Sol Ring", controller=0)

    actions.destroy(board.game, mine, source=outlet.id)
    board.sba()
    assert record.removal == []
