"""Which objects a resolved continuous effect applies to (CR 611.2c).

"If a continuous effect generated by the resolution of a spell or ability
modifies the characteristics or changes the controller of any objects, the set
of objects it affects is determined when that continuous effect begins. After
that point, the set won't change."

Only *targeted* effects were frozen. Every untargeted mass effect kept its
filter live and re-matched the board on every recomputation, so a pump that
read "creatures you control get +2/+2 until end of turn" also pumped creatures
that entered afterwards - the commonest shape of combat trick in the format,
paired with the commonest shape of token maker.

The rule's other half matters too: an effect that modifies neither
characteristics nor control is modifying the rules of the game, and *does*
apply to objects that were not there when it began.
"""

from __future__ import annotations

from harness import make_board

from mtgfish.rules.effects import Effect, EffectKind
from mtgfish.rules.enums import CardType, Duration
from mtgfish.rules.ids import NO_OBJECT, PlayerId
from mtgfish.rules.query import ControllerRelation, ObjectFilter
from mtgfish.rules.resolve import Resolution, _register_continuous
from mtgfish.rules.restrictions import Act, Restriction, prohibited, register_standing
from mtgfish.rules.values import Value

YOUR_CREATURES = ObjectFilter(
    types_all=CardType.CREATURE, controller=ControllerRelation.YOU
)


def _resolve(board, effect, controller=0):
    _register_continuous(
        Resolution(game=board.game, source=NO_OBJECT, controller=PlayerId(controller)),
        effect,
    )
    board.refresh()


def _mass_pump(duration=Duration.END_OF_TURN):
    return Effect(
        EffectKind.MODIFY_PT,
        amount=Value(constant=2),
        amount2=Value(constant=2),
        targets=YOUR_CREATURES,
        duration=int(duration),
    )


def test_it_applies_to_what_was_there(card_db):
    board = make_board(card_db)
    bear = board.play("Grizzly Bears", 0)
    _resolve(board, _mass_pump())
    assert board.pt(bear) == (4, 4)


def test_it_does_not_reach_a_creature_that_arrives_later(card_db):
    """The rule's own example, in the shape the format actually plays it."""
    board = make_board(card_db)
    board.play("Grizzly Bears", 0)
    _resolve(board, _mass_pump())

    latecomer = board.play("Grizzly Bears", 0)
    assert board.pt(latecomer) == (2, 2)


def test_every_creature_present_is_caught(card_db):
    board = make_board(card_db)
    first = board.play("Grizzly Bears", 0)
    second = board.play("Savannah Lions", 0)
    _resolve(board, _mass_pump())
    assert board.pt(first) == (4, 4)
    assert board.pt(second) == (4, 3)


def test_an_opponents_creature_is_not_caught(card_db):
    board = make_board(card_db)
    theirs = board.play("Grizzly Bears", 1)
    _resolve(board, _mass_pump())
    assert board.pt(theirs) == (2, 2)


def test_an_effect_that_matches_nothing_stays_harmless(card_db):
    """An empty set must not be registered as "no constraint".

    ObjectFilter reads an empty ``specific`` tuple as no constraint at all, so
    freezing an empty set naively would apply the effect to every object on
    the board - the opposite of what the rule says.
    """
    board = make_board(card_db)
    _resolve(board, _mass_pump())

    arrival = board.play("Grizzly Bears", 0)
    assert board.pt(arrival) == (2, 2)


def test_a_rules_modifying_effect_still_reaches_later_objects(card_db):
    """CR 611.2c's second half: it modifies the rules, so the set stays open.

    A prohibition changes no characteristic and no controller, so a creature
    that arrives after it resolved is bound by it too.
    """
    board = make_board(card_db)
    register_standing(
        board.game,
        Restriction(
            act=Act.ATTACK,
            subject=YOUR_CREATURES,
            controller=PlayerId(0),
            duration=int(Duration.END_OF_TURN),
            text="creatures can't attack this turn",
        ),
    )
    board.refresh()

    latecomer = board.play("Grizzly Bears", 0)
    assert prohibited(board.game, Act.ATTACK, obj=latecomer) is not None
