"""Timestamps of granted abilities (CR 613.7a).

A continuous effect generated by a static ability takes the object's timestamp
or the granting effect's, whichever is later. The engine harvested every static
ability off an object and stamped all of them with the object's own timestamp,
so an ability granted long afterwards applied as though it had been printed on
the card - and lost every ordering contest against effects created in between.
"""

from __future__ import annotations

import pytest
from harness import ScriptedAbilities, make_board

from mtgfish.rules.cr600_spells_and_abilities.abilities import Ability, AbilityKind
from mtgfish.rules.cr600_spells_and_abilities.effects import Effect, EffectKind
from mtgfish.rules.cr600_spells_and_abilities.resolve import Resolution, _register_continuous
from mtgfish.rules.kernel.enums import CardType, Duration
from mtgfish.rules.kernel.ids import NO_OBJECT, PlayerId
from mtgfish.rules.kernel.query import ObjectFilter
from mtgfish.rules.kernel.values import Value

CREATURES = ObjectFilter(types_all=CardType.CREATURE)


@pytest.fixture
def board(card_db):
    return make_board(card_db, ScriptedAbilities())


def _set_pt(power: int, toughness: int, text: str) -> Effect:
    return Effect(
        EffectKind.SET_PT,
        amount=Value(constant=power),
        amount2=Value(constant=toughness),
        text=text,
    )


def _static(effect: Effect, text: str) -> Ability:
    return Ability(AbilityKind.STATIC, effects=(effect,), text=text)


def _resolve(board, effect: Effect, controller: int = 0) -> None:
    """A spell resolving and creating a continuous effect (CR 611.2)."""
    _register_continuous(
        Resolution(game=board.game, source=NO_OBJECT, controller=PlayerId(controller)),
        effect,
    )
    board.refresh()


def _grant(board, obj, ability: Ability, controller: int = 0) -> None:
    _resolve(
        board,
        Effect(
            EffectKind.GRANT_ABILITY,
            targets=ObjectFilter(specific=(obj.id,)),
            granted_abilities=(ability,),
            duration=int(Duration.PERMANENT),
        ),
        controller,
    )


def test_a_granted_ability_beats_an_effect_created_before_the_grant(board):
    """CR 613.7a: the ability takes the granting effect's timestamp, which is
    later than the anthem's, so it applies last."""
    bear = board.play("Grizzly Bears", controller=0)

    # Timestamp 2: "creatures have base power and toughness 2/2".
    _resolve(
        board,
        Effect(
            EffectKind.SET_PT,
            targets=CREATURES,
            amount=Value(constant=2),
            amount2=Value(constant=2),
            duration=int(Duration.PERMANENT),
            text="creatures have base power and toughness 2/2",
        ),
    )
    assert board.pt(bear) == (2, 2)

    # Timestamp 3: the bear gains "this creature has base power and
    # toughness 5/5". The bear's own timestamp is earlier than the 2/2 effect.
    _grant(board, bear, _static(_set_pt(5, 5, "base 5/5"), "has base 5/5"))

    assert board.pt(bear) == (5, 5)


def test_a_grant_made_first_still_loses_to_a_later_effect(board):
    """The control: with the grant made first, the later effect wins. Nothing
    here makes a granted ability win on principle - only on timestamp."""
    bear = board.play("Grizzly Bears", controller=0)

    _grant(board, bear, _static(_set_pt(5, 5, "base 5/5"), "has base 5/5"))
    assert board.pt(bear) == (5, 5)

    _resolve(
        board,
        Effect(
            EffectKind.SET_PT,
            targets=CREATURES,
            amount=Value(constant=2),
            amount2=Value(constant=2),
            duration=int(Duration.PERMANENT),
            text="creatures have base power and toughness 2/2",
        ),
    )

    assert board.pt(bear) == (2, 2)


def test_a_printed_ability_keeps_the_object_timestamp(board):
    """CR 613.7a's first half: a printed static ability is stamped with the
    object, so an effect created afterwards applies after it."""
    board.scripts.add("Grizzly Bears", _static(_set_pt(5, 5, "base 5/5"), "has base 5/5"))
    bear = board.play("Grizzly Bears", controller=0)
    assert board.pt(bear) == (5, 5)

    _resolve(
        board,
        Effect(
            EffectKind.SET_PT,
            targets=CREATURES,
            amount=Value(constant=2),
            amount2=Value(constant=2),
            duration=int(Duration.PERMANENT),
            text="creatures have base power and toughness 2/2",
        ),
    )

    assert board.pt(bear) == (2, 2)
